blueprint:
  name: Lumières selon aspirateur (avec gestion optionnelle de présence)
  description: >
    Allume/éteint les lumières selon la pièce où se trouve le robot aspirateur.
    Les lumières s’allument à 100% quand le robot démarre ou entre dans une pièce,
    et s’éteignent quand il quitte ou s’arrête. La gestion de la présence est optionnelle.
  domain: automation
  input:
    vacuum_entity:
      name: Entité aspirateur
      description: Entité du robot aspirateur (vacuum.xxx)
      selector:
        entity:
          domain: vacuum
    room_sensor:
      name: Capteur de pièce
      description: Entité sensor indiquant la pièce actuelle du robot
      selector:
        entity:
          domain: sensor
    lights_mapping:
      name: Mapping pièces → lumières
      description: Associez les noms de pièces du robot aux entités lumières correspondantes
      selector:
        object:
    presence_entities:
      name: Entités de présence (optionnel)
      description: Liste des entités de présence (person.xxx). Si vide, pas de condition de présence.
      default: []
      selector:
        entity:
          domain: person
          multiple: true

trigger:
  - platform: state
    entity_id: !input room_sensor
  - platform: state
    entity_id: !input vacuum_entity

condition: []
action:
  - variables:
      room: "{{ states(room_sensor) }}"
      previous_room: "{{ trigger.from_state.state if trigger.entity_id == room_sensor else '' }}"
      vacuum_state: "{{ states(vacuum_entity) }}"
      lights_map: !input lights_mapping
      presence_entities: !input presence_entities

  - choose:
      # Gestion de la présence (si des entités sont renseignées)
      - conditions:
          - condition: template
            value_template: >
              {% if presence_entities | length > 0 %}
                {{ expand(presence_entities) | selectattr('state','eq','home') | list | length == 0 }}
              {% else %}
                true
              {% endif %}
        sequence:
          - choose:
              # Cas 1 : robot démarre ou reprend
              - conditions:
                  - condition: template
                    value_template: "{{ vacuum_state in ['cleaning','returning'] and room in lights_map }}"
                sequence:
                  - service: light.turn_on
                    data:
                      brightness_pct: 100
                    target:
                      entity_id: "{{ lights_map[room] }}"

              # Cas 2 : robot s’arrête, pause, erreur ou dock
              - conditions:
                  - condition: template
                    value_template: "{{ vacuum_state in ['paused','error','idle','docked'] and room in lights_map }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ lights_map[room] }}"

              # Cas 3 : changement de pièce pendant nettoyage
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.entity_id == room_sensor and vacuum_state in ['cleaning','returning'] }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ room in lights_map }}"
                        sequence:
                          - service: light.turn_on
                            data:
                              brightness_pct: 100
                            target:
                              entity_id: "{{ lights_map[room] }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ previous_room in lights_map }}"
                        sequence:
                          - service: light.turn_off
                            target:
                              entity_id: "{{ lights_map[previous_room] }}"

mode: restart
