blueprint:
  name: Lumières selon aspirateur (présence + luminosité optionnelles)
  description: >
    Allume/éteint les lumières selon la pièce où se trouve le robot aspirateur.
    Les lumières s’allument à 100% quand le robot démarre ou entre dans une pièce,
    et s’éteignent quand il quitte ou s’arrête.
    La gestion de la présence et de la luminosité ambiante est optionnelle.
  domain: automation
  input:
    vacuum_entity:
      name: Entité aspirateur
      description: Entité du robot aspirateur (vacuum.xxx)
      selector:
        entity:
          domain: vacuum
    room_sensor:
      name: Capteur de pièce
      description: Entité sensor indiquant la pièce actuelle du robot
      selector:
        entity:
          domain: sensor
    lights_mapping_text:
      name: Mapping pièces → lumières (JSON)
      description: >
        Collez un dictionnaire JSON, par ex :
        {"WC":"light.lumiere_wc","Salon":"light.lumieres_salon"}
      selector:
        text: {}
    presence_entities:
      name: Entités de présence (optionnel)
      description: Liste des entités de présence (person.xxx). Si vide, pas de condition de présence.
      default: []
      selector:
        entity:
          domain: person
          multiple: true
    light_sensor:
      name: Capteur de luminosité (optionnel)
      description: Entité sensor de luminosité (lux). Si vide, pas de condition de luminosité.
      default: ""
      selector:
        entity:
          domain: sensor
    light_threshold:
      name: Seuil de luminosité (lux)
      description: Valeur au-dessus de laquelle le scénario ne s’exécute pas
      default: 100
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: lux

trigger:
  - platform: state
    entity_id: !input room_sensor
  - platform: state
    entity_id: !input vacuum_entity

action:
  - variables:
      room: "{{ states(!input room_sensor) }}"
      previous_room: "{{ trigger.from_state.state if trigger.entity_id == !input room_sensor else '' }}"
      vacuum_state: "{{ states(!input vacuum_entity) }}"
      lights_map: "{{ !input lights_mapping_text | from_json }}"
      presence_entities: !input presence_entities
      light_sensor: !input light_sensor
      light_threshold: !input light_threshold

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set presence_ok = (
                presence_entities | length == 0 or
                (expand(presence_entities) | selectattr('state','eq','home') | list | length == 0)
              ) %}
              {% set lux_ok = (
                light_sensor == "" or
                (states(light_sensor) | float(0) <= light_threshold)
              ) %}
              {{ presence_ok and lux_ok }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ vacuum_state in ['cleaning','returning'] and room in lights_map }}"
                sequence:
                  - service: light.turn_on
                    data:
                      brightness_pct: 100
                    target:
                      entity_id: "{{ lights_map[room] }}"
              - conditions:
                  - condition: template
                    value_template: "{{ vacuum_state in ['paused','error','idle','docked'] and room in lights_map }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ lights_map[room] }}"
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.entity_id == !input room_sensor and vacuum_state in ['cleaning','returning'] }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ room in lights_map }}"
                        sequence:
                          - service: light.turn_on
                            data:
                              brightness_pct: 100
                            target:
                              entity_id: "{{ lights_map[room] }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ previous_room in lights_map }}"
                        sequence:
                          - service: light.turn_off
                            target:
                              entity_id: "{{ lights_map[previous_room] }}"

mode: restart
