blueprint:
  name: Lumières robot aspirateur (absence + DND + luminosité)
  description: >
    Version optimisée. Allume/éteint les lumières selon la pièce du robot.
    Options :
    - Gestion de présence activable
    - Luminosité facultative (capteur requis uniquement si option activée)
    - DND avec gestion minuit
    - Choix de luminosité fixe ou précédente
  domain: automation

  input:

    robot_entity:
      name: Robot aspirateur
      selector:
        entity:
          domain: vacuum

    current_room_sensor:
      name: Capteur de pièce actuelle
      selector:
        entity:
          domain: sensor

    room_light_mapping:
      name: Mapping pièces → lumières
      default: {}
      selector:
        object:

    ###########################################################
    # --- PRÉSENCE (désactivable) ---
    ###########################################################

    enable_presence_check:
      name: Activer la gestion de présence
      default: true
      selector:
        boolean:

    presence_entities:
      name: Entités de présence
      selector:
        target:
          entity:
            domain: person

    presence_state:
      name: État indiquant une présence
      default: "home"
      selector:
        text:

    ###########################################################
    # --- DND ---
    ###########################################################

    enable_dnd:
      name: Activer le mode DND
      default: false
      selector:
        boolean:

    dnd_start_time:
      name: Début DND
      default: "22:30"
      selector:
        time:

    dnd_end_time:
      name: Fin DND
      default: "08:00"
      selector:
        time:

    ###########################################################
    # --- LUMINOSITÉ (désactivable) ---
    ###########################################################

    enable_luminosity_check:
      name: Activer le contrôle luminosité
      default: false
      selector:
        boolean:

    luminosity_sensor:
      name: Capteur de luminosité
      description: Facultatif si le contrôle luminosité est désactivé
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    luminosity_threshold:
      name: Seuil lux
      default: 50
      selector:
        number:
          min: 0
          max: 2000
          step: 5

    ###########################################################
    # --- LUMINOSITÉ LAMPES ---
    ###########################################################

    brightness_mode:
      name: Mode de luminosité
      default: "fixed"
      selector:
        select:
          options:
            - label: "Conserver la luminosité précédente"
              value: "previous"
            - label: "Définir un pourcentage fixe"
              value: "fixed"

    brightness_value:
      name: Luminosité fixe (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1


mode: restart

trigger:
  - platform: state
    entity_id: !input robot_entity

  - platform: state
    entity_id: !input current_room_sensor

  - platform: time
    at: !input dnd_start_time

  - platform: time
    at: !input dnd_end_time


variables:

  robot: !input robot_entity
  room_sensor: !input current_room_sensor
  mapping: !input room_light_mapping

  # Options
  enable_presence: !input enable_presence_check
  enable_lux: !input enable_luminosity_check

  brightness_mode: !input brightness_mode
  brightness_value: !input brightness_value
  presence_state: !input presence_state
  luminosity_threshold: !input luminosity_threshold

  current_room: "{{ states(room_sensor) }}"

  previous_room: >
    {% if trigger.platform == 'state' and trigger.entity_id == room_sensor %}
      {{ trigger.from_state.state }}
    {% else %}
      {{ none }}
    {% endif %}

  previous_light: >
    {% if previous_room in mapping %}
      {{ mapping[previous_room] }}
    {% endif %}

  # États robot
  is_running: "{{ state_attr(robot, 'running') }}"
  is_paused: "{{ state_attr(robot, 'paused') }}"
  is_charging: "{{ state_attr(robot, 'charging') }}"
  is_docked: "{{ state_attr(robot, 'docked') }}"

  ###########################################################
  # PRÉSENCE (désactivable)
  ###########################################################
  is_everyone_absent: >
    {% if not enable_presence %}
      true
    {% else %}
      {% set targets = input('presence_entities') %}
      {% set present = false %}
      {% for p in targets.entity_id %}
        {% if states(p) == presence_state %}
          {% set present = true %}
        {% endif %}
      {% endfor %}
      {{ not present }}
    {% endif %}

  ###########################################################
  # LUMINOSITÉ (capteur facultatif si désactivé)
  ###########################################################
  is_too_bright: >
    {% if not enable_lux %}
      false
    {% else %}
      {% set sensor = input('luminosity_sensor') %}
      {% if sensor == none %}
        false
      {% else %}
        {{ states(sensor) | float > luminosity_threshold }}
      {% endif %}
    {% endif %}

  ###########################################################
  # DND
  ###########################################################
  is_dnd_active: >
    {% if not input('enable_dnd') %}
      false
    {% else %}
      {% set now_m = now().hour*60 + now().minute %}
      {% set s = str(input('dnd_start_time')).split(':') %}
      {% set e = str(input('dnd_end_time')).split(':') %}
      {% set start_m = s[0]|int*60 + s[1]|int %}
      {% set end_m = e[0]|int*60 + e[1]|int %}
      {% if end_m > start_m %}
        {{ start_m <= now_m < end_m }}
      {% else %}
        {{ now_m >= start_m or now_m < end_m }}
      {% endif %}
    {% endif %}


action:

  ############################################################
  # 1️⃣ Allumer dans la pièce actuelle
  ############################################################
  - choose:
      - conditions:
          - "{{ current_room in mapping }}"
          - "{{ is_running }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
          - "{{ not is_too_bright }}"
        sequence:
          - choose:
              - conditions: "{{ brightness_mode == 'fixed' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ mapping[current_room] }}"
                    data:
                      brightness_pct: "{{ brightness_value }}"
            default:
              - service: light.turn_on
                target:
                  entity_id: "{{ mapping[current_room] }}"


  ############################################################
  # 2️⃣ Éteindre la pièce quittée
  ############################################################
  - choose:
      - conditions:
          - "{{ previous_light is not none }}"
          - "{{ previous_room != current_room }}"
          - "{{ is_running }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ previous_light }}"


  ############################################################
  # 3️⃣ Éteindre la pièce actuelle si le robot stoppe
  ############################################################
  - choose:
      - conditions:
          - "{{ current_room in mapping }}"
          - "{{ is_paused or is_charging or is_docked }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
        sequence:
          - delay:
              seconds: >
                {% if is_docked %} 15
                {% else %} 60
                {% endif %}
          - service: light.turn_off
            target:
              entity_id: "{{ mapping[current_room] }}"
