blueprint:
  name: Lumières robot aspirateur (absence + DND + luminosité) - simplifié
  description: >
    Allume/éteint les lumières selon la pièce détectée par le robot.
    Gère présence, DND et luminosité. Plus de triggers time nécessaires.
  domain: automation

  input:
    robot_entity:
      name: Robot aspirateur
      selector:
        entity:
          domain: vacuum
    current_room_sensor:
      name: Capteur pièce actuelle
      selector:
        entity:
          domain: sensor
    room_light_mapping:
      name: Mapping pièces vers lumières
      selector:
        object:
    enable_presence_check:
      name: Activer gestion de présence
      default: false
      selector:
        boolean:
    presence_entities:
      name: Entités de présence
      default: []
      selector:
        entity:
          multiple: true
          domain: person
    presence_state:
      name: État = présent
      default: "Maison"
      selector:
        text:
    enable_dnd:
      name: Activer DND
      default: false
      selector:
        boolean:
    dnd_start_time:
      name: Début DND
      default: "22:30"
      selector:
        time:
    dnd_end_time:
      name: Fin DND
      default: "08:00"
      selector:
        time:
    enable_luminosity_check:
      name: Activer contrôle luminosité
      default: false
      selector:
        boolean:
    luminosity_sensor:
      name: Capteur de luminosité (optionnel)
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    luminosity_threshold:
      name: Seuil lux
      default: 50
      selector:
        number:
          min: 0
          max: 2000
          step: 5
    brightness_mode:
      name: Mode luminosité
      default: "fixed"
      selector:
        select:
          options:
            - label: "Conserver précédente"
              value: "previous"
            - label: "Fixer un pourcentage"
              value: "fixed"
    brightness_value:
      name: Pourcentage fixe
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1

mode: single

trigger:
  - platform: state
    entity_id: !input current_room_sensor
  - platform: state
    entity_id: !input robot_entity
    attribute: running
  - platform: state
    entity_id: !input robot_entity
    attribute: paused
  - platform: state
    entity_id: !input robot_entity
    attribute: charging
  - platform: state
    entity_id: !input robot_entity
    attribute: docked

variables:
  robot: !input robot_entity
  room_sensor: !input current_room_sensor
  mapping: !input room_light_mapping
  current_room: "{{ states(room_sensor) }}"
  previous_room: >
    {% if trigger.platform == 'state' and trigger.entity_id == room_sensor %}
      {{ trigger.from_state.state | default('') }}
    {% else %}
      {{ '' }}
    {% endif %}
  previous_light: "{{ mapping.get(previous_room) }}"
  is_running: >
    {{ state_attr(robot, 'running') | default(false) or
       state_attr(robot, 'zone_cleaning') | default(false) or
       state_attr(robot, 'segment_cleaning') | default(false) or
       state_attr(robot, 'spot_cleaning') | default(false) }}
  is_paused_or_docked: >
    {{ state_attr(robot, 'paused') | default(false) or
       state_attr(robot, 'charging') | default(false) or
       state_attr(robot, 'docked') | default(false) }}
  was_paused_or_docked: >
    {% if trigger.platform == 'state' and trigger.entity_id == robot %}
      {{ trigger.from_state.attributes.paused | default(false) or
         trigger.from_state.attributes.charging | default(false) or
         trigger.from_state.attributes.docked | default(false) }}
    {% else %}
      false
    {% endif %}
  is_resuming: "{{ was_paused_or_docked and is_running }}"
  enable_presence: !input enable_presence_check
  is_everyone_absent: >
    {% if not enable_presence or (presence_entities | length == 0) %}
      true
    {% else %}
      {% set absent = true %}
      {% for p in presence_entities %}
        {% if states(p) == presence_state %}
          {% set absent = false %}
        {% endif %}
      {% endfor %}
      {{ absent }}
    {% endif %}
  enable_lux: !input enable_luminosity_check
  luminosity_sensor_input: "{{ luminosity_sensor | default('') }}"
  is_too_bright: >
    {% if not enable_lux or luminosity_sensor_input == '' %}
      false
    {% else %}
      {{ states(luminosity_sensor_input) | float > luminosity_threshold }}
    {% endif %}
  enable_dnd_input: !input enable_dnd
  is_dnd_active: >
    {% if not enable_dnd_input %}
      false
    {% else %}
      {% set now_m = now().hour*60 + now().minute %}
      {% set s = str(dnd_start_time).split(':') %}
      {% set e = str(dnd_end_time).split(':') %}
      {% set start_m = s[0]|int*60 + s[1]|int %}
      {% set end_m = e[0]|int*60 + e[1]|int %}
      {% if end_m > start_m %}
        {{ start_m <= now_m < end_m }}
      {% else %}
        {{ now_m >= start_m or now_m < end_m }}
      {% endif %}
    {% endif %}

action:
  # Allumer la pièce actuelle
  - choose:
      - conditions:
          - "{{ current_room in mapping }}"
          - "{{ is_running or is_resuming }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
          - "{{ not is_too_bright }}"
        sequence:
          - choose:
              - conditions: "{{ brightness_mode == 'fixed' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ mapping[current_room] }}"
                    data:
                      brightness_pct: "{{ brightness_value }}"
            default:
              - service: light.turn_on
                target:
                  entity_id: "{{ mapping[current_room] }}"

  # Éteindre la pièce quittée
  - choose:
      - conditions:
          - "{{ previous_light is not none }}"
          - "{{ previous_room != current_room }}"
          - "{{ is_running }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ previous_light }}"

  # Éteindre la pièce actuelle si robot stop/paused/dock
  - choose:
      - conditions:
          - "{{ current_room in mapping }}"
          - "{{ is_paused_or_docked }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
        sequence:
          - delay:
              seconds: >
                {% if state_attr(robot, 'docked') | default(false) %} 15
                {% else %} 60
                {% endif %}
          - service: light.turn_off
            target:
              entity_id: "{{ mapping[current_room] }}"
