blueprint:
  name: Lumières robot aspirateur – simple
  description: >
    Allume et éteint les lumières selon la pièce et l'état du robot.
    Options : présence, DND et luminosité (optionnelles).
  domain: automation
  input:
    ###########################################################################
    # ROBOT & PIÈCES
    ###########################################################################
    robot_entity:
      name: Robot aspirateur
      description: 'Ex : vacuum.l40s_pro_ultra'
      selector:
        entity:
          domain: vacuum
    current_room_sensor:
      name: Capteur pièce actuelle
      description: 'Ex : sensor.l40s_pro_ultra_current_room'
      selector:
        entity:
          domain: sensor
    room_light_mapping:
      name: Mapping pièces → lumières
      description: >
        JSON des pièces et leurs lumières. Ex : 
        { "WC": "light.lumiere_wc", "Chambre": "light.lumiere_chambre" }
      selector:
        text:

    ###########################################################################
    # OPTIONS (facultatives)
    ###########################################################################
    enable_presence_check:
      name: Activer présence
      description: 'Bloque l’allumage si quelqu’un est présent.'
      default: false
      selector:
        boolean
    presence_entities:
      name: Entités présence
      description: 'Liste des entités de présence (person.gwen, person.vincent)'
      default: []
      selector:
        entity:
          multiple: true
          domain: person
    presence_state:
      name: État = présent
      description: 'Ex : Maison'
      default: "Maison"
      selector:
        text:

    enable_dnd:
      name: Activer DND
      description: 'Bloque l’automatisation pendant une plage horaire.'
      default: false
      selector:
        boolean
    dnd_start_time:
      name: Début DND
      default: "22:30"
      selector:
        time
    dnd_end_time:
      name: Fin DND
      default: "08:00"
      selector:
        time

    enable_luminosity_check:
      name: Activer luminosité
      description: 'Évite d’allumer si pièce déjà lumineuse.'
      default: false
      selector:
        boolean
    luminosity_sensor:
      name: Capteur luminosité (optionnel)
      description: 'Laisser vide si non utilisé.'
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    luminosity_threshold:
      name: Seuil lux
      description: 'Allumage si luminosité < seuil.'
      default: 50
      selector:
        number:
          min: 0
          max: 2000
          step: 5

    brightness_mode:
      name: Mode luminosité
      description: 'Fixe ou dernière valeur utilisée.'
      default: "fixed"
      selector:
        select:
          options:
            - label: "Conserver précédente"
              value: "previous"
            - label: "Fixer un pourcentage"
              value: "fixed"
    brightness_value:
      name: Pourcentage fixe
      description: 'Si mode fixe'
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1

mode: single

trigger:
  - platform: state
    entity_id: !input robot_entity
  - platform: state
    entity_id: !input current_room_sensor

variables:
  robot: !input robot_entity
  room_sensor: !input current_room_sensor
  mapping: "{{ room_light_mapping | from_json }}"
  enable_presence: !input enable_presence_check
  enable_lux: !input enable_luminosity_check
  enable_dnd: !input enable_dnd
  brightness_mode: !input brightness_mode
  brightness_value: !input brightness_value
  presence_state: !input presence_state
  luminosity_threshold: !input luminosity_threshold

  # Pièce actuelle et précédente
  current_room: "{{ states(room_sensor) }}"
  previous_room: >
    {% if trigger.platform == 'state' and trigger.entity_id == room_sensor %}
      {{ trigger.from_state.state }}
    {% else %}
      {{ none }}
    {% endif %}
  previous_light: >
    {% if previous_room in mapping %}
      {{ mapping[previous_room] }}
    {% else %}
      {{ none }}
    {% endif %}

  # États robot
  is_running: "{{ state_attr(robot, 'running') or state_attr(robot, 'zone_cleaning') or state_attr(robot, 'segment_cleaning') or state_attr(robot, 'spot_cleaning') }}"
  is_paused_or_docked: "{{ state_attr(robot, 'paused') or state_attr(robot, 'charging') or state_attr(robot, 'docked') }}"
  was_paused_or_docked: >
    {% if trigger.platform == 'state' and trigger.entity_id == robot %}
      {{ trigger.from_state.attributes.paused or trigger.from_state.attributes.charging or trigger.from_state.attributes.docked }}
    {% else %}
      false
    {% endif %}
  is_resuming: "{{ was_paused_or_docked and is_running }}"

  # Présence
  is_everyone_absent: >
    {% if not enable_presence %}
      true
    {% else %}
      {% set absent = true %}
      {% for p in presence_entities %}
        {% if states(p) == presence_state %}
          {% set absent = false %}
        {% endif %}
      {% endfor %}
      {{ absent }}
    {% endif %}

  # Luminosité
  is_too_bright: >
    {% if not enable_lux or not luminosity_sensor %}
      false
    {% else %}
      {{ states(luminosity_sensor) | float > luminosity_threshold }}
    {% endif %}

  # DND
  is_dnd_active: >
    {% if not enable_dnd %}
      false
    {% else %}
      {% set now_m = now().hour*60 + now().minute %}
      {% set s = str(dnd_start_time).split(':') %}
      {% set e = str(dnd_end_time).split(':') %}
      {% set start_m = s[0]|int*60 + s[1]|int %}
      {% set end_m = e[0]|int*60 + e[1]|int %}
      {% if end_m > start_m %}
        {{ start_m <= now_m < end_m }}
      {% else %}
        {{ now_m >= start_m or now_m < end_m }}
      {% endif %}
    {% endif %}

action:
  # Allumer la lumière de la pièce actuelle
  - choose:
      - conditions:
          - "{{ current_room in mapping }}"
          - "{{ is_running or is_resuming }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
          - "{{ not is_too_bright }}"
        sequence:
          - choose:
              - conditions: "{{ brightness_mode == 'fixed' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ mapping[current_room] }}"
                    data:
                      brightness_pct: "{{ brightness_value }}"
            default:
              - service: light.turn_on
                target:
                  entity_id: "{{ mapping[current_room] }}"

  # Éteindre la pièce précédente
  - choose:
      - conditions:
          - "{{ previous_light is not none }}"
          - "{{ previous_room != current_room }}"
          - "{{ is_running }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ previous_light }}"

  # Éteindre la pièce actuelle si robot pause/charge/dock
  - choose:
      - conditions:
          - "{{ current_room in mapping }}"
          - "{{ is_paused_or_docked }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
        sequence:
          - delay: >
              {% if state_attr(robot, 'docked') %} 15
              {% else %} 60
              {% endif %}
          - service: light.turn_off
            target:
              entity_id: "{{ mapping[current_room] }}"
