blueprint:
  name: Lumières robot aspirateur (absence + DND + luminosité)
  description: >
    Version optimisée et enrichie avec guide utilisateur.
    Allume/éteint les lumières selon la pièce du robot.
    Fonctionne même sans présence ou sans capteur de luminosité.
    Sections : Robot, Lumières, Présence, DND, Luminosité.

  domain: automation

  ###########################################################################
  # 🧹 SECTION : ROBOT / POSITION
  ###########################################################################
  input:

    robot_entity:
      name: Robot aspirateur
      description: >
        Sélectionnez l'entité du robot aspirateur.
        Exemple : **vacuum.roborock_s7**, **vacuum.l40s_pro_ultra**
      selector:
        entity:
          domain: vacuum

    current_room_sensor:
      name: Capteur de pièce actuelle du robot
      description: >
        Capteur fournissant le nom de la pièce où se trouve le robot.
        Exemple : **sensor.roborock_current_room**
      selector:
        entity:
          domain: sensor

    room_light_mapping:
      name: Mapping pièces → lumières
      description: >
        Permet d'associer chaque pièce à une lumière.
        Format attendu :
        ```
        {"Salon": "light.salon", "Cuisine": "light.cuisine"}
        ```
        La pièce doit correspondre EXACTEMENT au nom envoyé par le capteur.
      default: {}
      selector:
        object:


  ###########################################################################
  # 👤 SECTION : GESTION DE LA PRÉSENCE (facultative)
  ###########################################################################

    enable_presence_check:
      name: Activer la gestion de présence
      description: >
        Si activé : les lumières ne s'allument que si **tous les occupants sont absents**.
        Si désactivé : la présence n'est pas prise en compte → fonctionne même si vous êtes à la maison.
      default: true
      selector:
        boolean:

    presence_entities:
      name: Entités de présence
      description: >
        Choisissez les entités de type *person* à surveiller.
        Exemple : person.vincent, person.gwen.
        Ignoré si la présence est désactivée.
      selector:
        target:
          entity:
            domain: person

    presence_state:
      name: État indiquant une présence
      description: >
        État utilisé pour considérer qu'une personne est "chez elle".
        Par défaut : **home**.
        Exemples : "home", "Maison", "Présent".
      default: "home"
      selector:
        text:


  ###########################################################################
  # 🌙 SECTION : DO NOT DISTURB (DND)
  ###########################################################################

    enable_dnd:
      name: Activer le mode DND
      description: >
        Empêche tout allumage/éclairage automatique pendant une plage horaire.
        Utile la nuit ou pendant des heures sensibles.
      default: false
      selector:
        boolean:

    dnd_start_time:
      name: Début du DND
      description: >
        Heure à partir de laquelle l'automatisation doit se désactiver.
        Exemple : **22:30**
      default: "22:30"
      selector:
        time:

    dnd_end_time:
      name: Fin du DND
      description: >
        Heure à laquelle l'automatisation redevient active.
        Exemple : **08:00**
        Fonctionne même si la plage passe minuit.
      default: "08:00"
      selector:
        time:


  ###########################################################################
  # ☀️ SECTION : CONTRÔLE DE LUMINOSITÉ
  ###########################################################################

    enable_luminosity_check:
      name: Activer le contrôle luminosité
      description: >
        Si activé : les lumières ne s'allument que s'il fait suffisamment sombre.
        Si désactivé : aucun capteur n'est requis.
      default: false
      selector:
        boolean:

    luminosity_sensor:
      name: Capteur de luminosité
      description: >
        Capteur mesurant la luminosité ambiante.
        Exemple : **sensor.lux_salon**
        Non obligatoire si le contrôle luminosité est désactivé.
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    luminosity_threshold:
      name: Seuil de luminosité (lux)
      description: >
        Si le capteur indique plus que cette valeur, la lumière ne s'allume pas.
        Exemples : 20 (très sombre), 80 (normal), 200 (clair).
      default: 50
      selector:
        number:
          min: 0
          max: 2000
          step: 5


  ###########################################################################
  # 💡 SECTION : MODE DE LUMINOSITÉ AU MOMENT DE L'ALLUMAGE
  ###########################################################################

    brightness_mode:
      name: Mode de luminosité à l'allumage
      description: >
        - **Conserver la luminosité précédente** : la lampe garde son dernier réglage.
        - **Définir un pourcentage fixe** : applique la luminosité définie ci-dessous.
      default: "fixed"
      selector:
        select:
          options:
            - label: "Conserver la luminosité précédente"
              value: "previous"
            - label: "Définir un pourcentage fixe"
              value: "fixed"

    brightness_value:
      name: Pourcentage fixe (%)
      description: >
        Pourcentage appliqué si le mode "Définir un pourcentage fixe" est sélectionné.
        Exemple : 30, 50, 100
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1


###############################################################################
# TRIGGERS, VARIABLES et ACTIONS
# (inchangés par rapport à la version précédemment fournie)
###############################################################################

# ⚠️ Le bloc triggers + variables + action reste le même
# pour éviter de dépasser la limite de message dans ChatGPT.

# 👉 Je peux te renvoyer TOUT le blueprint final complet en un seul bloc si tu veux.

