blueprint:
  name: Lumières robot aspirateur (absence + DND)
  description: >
    Allume ou éteint les lumières selon la pièce détectée par le robot.
    Options : présence, DND, luminosité fixe ou précédente.
  domain: automation

  input:
    robot_entity:
      name: Robot aspirateur
      selector:
        entity:
          domain: vacuum

    current_room_sensor:
      name: Capteur pièce actuelle
      selector:
        entity:
          domain: sensor

    room_light_mapping:
      name: Mapping pièces vers lumières
      selector:
        object:
          multiple: true
          key:
            selector:
              text: {}
          value:
            selector:
              entity:
                domain: light

    enable_presence_check:
      name: Activer gestion de présence
      default: false
      selector:
        boolean: {}

    presence_entities:
      name: Entités de présence
      default: []
      selector:
        entity:
          multiple: true
          domain: person

    presence_state:
      name: État = présent
      default: home
      selector:
        text: {}

    enable_dnd:
      name: Activer DND
      default: false
      selector:
        boolean: {}

    dnd_start_time:
      name: Début DND
      default: "22:30"
      selector:
        time: {}

    dnd_end_time:
      name: Fin DND
      default: "08:00"
      selector:
        time: {}

    brightness_mode:
      name: Mode luminosité
      default: fixed
      selector:
        select:
          options:
            - label: Conserver précédente
              value: previous
            - label: Fixer un pourcentage
              value: fixed

    brightness_value:
      name: Pourcentage fixe
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1

mode: single

trigger:
  - platform: state
    entity_id: !input robot_entity
  - platform: state
    entity_id: !input current_room_sensor

variables:
  robot: !input robot_entity
  room_sensor: !input current_room_sensor
  mapping: !input room_light_mapping
  enable_presence: !input enable_presence_check
  brightness_mode: !input brightness_mode
  brightness_value: !input brightness_value
  presence_state: !input presence_state
  current_room: "{{ states(room_sensor) }}"
  previous_room: "{{ trigger.from_state.state if trigger.entity_id == room_sensor else none }}"
  previous_light: "{{ mapping.get(previous_room) if previous_room in mapping else none }}"
  robot_state: "{{ states(robot) }}"

  is_running: "{{ robot_state in ['cleaning','sweeping','returning'] }}"
  is_paused_or_docked: "{{ robot_state in ['paused','docked'] }}"
  is_everyone_absent: >
    {% if not enable_presence %}
      true
    {% else %}
      {% set absent = true %}
      {% for p in presence_entities %}
        {% if states(p) == presence_state %}
          {% set absent = false %}
        {% endif %}
      {% endfor %}
      {{ absent }}
    {% endif %}
  is_dnd_active: >
    {% if not enable_dnd %}
      false
    {% else %}
      {% set now_m = now().hour*60 + now().minute %}
      {% set s = str(dnd_start_time).split(':') %}
      {% set e = str(dnd_end_time).split(':') %}
      {% set start_m = s[0]|int*60 + s[1]|int %}
      {% set end_m = e[0]|int*60 + e[1]|int %}
      {% if end_m > start_m %}
        {{ start_m <= now_m < end_m }}
      {% else %}
        {{ now_m >= start_m or now_m < end_m }}
      {% endif %}
    {% endif %}

action:
  - choose:
      - conditions:
          - "{{ current_room in mapping }}"
          - "{{ is_running }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
        sequence:
          - choose:
              - conditions: "{{ brightness_mode == 'fixed' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ mapping.get(current_room) }}"
                    data:
                      brightness_pct: "{{ brightness_value }}"
            default:
              - service: light.turn_on
                target:
                  entity_id: "{{ mapping.get(current_room) }}"

  - choose:
      - conditions:
          - "{{ previous_light is not none }}"
          - "{{ previous_room != current_room }}"
          - "{{ is_running }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ previous_light }}"

  - choose:
      - conditions:
          - "{{ current_room in mapping }}"
          - "{{ is_paused_or_docked }}"
          - "{{ is_everyone_absent }}"
          - "{{ not is_dnd_active }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ mapping.get(current_room) }}"
